/*
QUESTÃO 4
4. Crie uma visão que mostra os dependentes de médicos elaboradores que
possuem salário maior que 20000 R$ e que já realizaram pelo menos um 
exame com o nome de “Radiografia”.
*/

CREATE VIEW VIEW_DEPENDENTES AS
SELECT DEPENDENTE.CODIGO_DEPENDENTE, DEPENDENTE.CODIGO_MEDICO_ELABORADOR, DEPENDENTE.NOME, DEPENDENTE.IDADE, DEPENDENTE.SEXO
FROM DEPENDENTE
INNER JOIN MEDICO_ELABORADOR ON DEPENDENTE.CODIGO_MEDICO_ELABORADOR = MEDICO_ELABORADOR.CODIGO
INNER JOIN EXAME ON MEDICO_ELABORADOR.CODIGO = EXAME.CODIGO_MEDICO_ELABORADOR
WHERE MEDICO_ELABORADOR.SALARIO > 20000
AND EXAME.NOME_EXAME = 'Radiografia';
